apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config-basic
  namespace: logging-basic

data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info

    [INPUT]
        Name         tail
        Path         /var/log/containers/*.log
        Parser       docker
        Tag          kube.*

    [FILTER]
        Name         grep
        Match        *
        Regex        log ERROR

    [OUTPUT]
        Name         stdout
        Match        *
