apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: hpa-lab

spec:
  replicas: 2

  selector:
    matchLabels:
      app: php-apache

  template:
    metadata:
      labels:
        app: php-apache

    spec:
      containers:
      - name: php-apache
        image: nginx:1.29

        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
